# Generated by Django 4.0.4 on 2022-05-29 06:33

from django.db import migrations, models
import django.db.models.deletion
import modals.models


class Migration(migrations.Migration):

    dependencies = [
        ('modals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=modals.models.user_directory_path)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='modals.notecategory'),
        ),
    ]
