# Generated by Django 4.0.4 on 2022-05-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modals', '0002_file_alter_note_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
