# Generated by Django 4.0.4 on 2022-05-29 08:00

from django.db import migrations, models
import modals.models


class Migration(migrations.Migration):

    dependencies = [
        ('modals', '0003_file_time_alter_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default='default', upload_to=modals.models.user_directory_path),
        ),
    ]
