# Generated by Django 4.0.4 on 2022-06-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modals', '0004_file_name_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svg',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
