# Generated by Django 4.0.4 on 2022-06-25 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modals', '0007_note_name_alter_note_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorandumCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'memorandum_category',
            },
        ),
        migrations.CreateModel(
            name='Memorandum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField(blank=True, max_length=100000)),
                ('time', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorandums', to='modals.memorandumcategory')),
            ],
            options={
                'db_table': 'memorandum',
            },
        ),
    ]
