# Generated by Django 4.0.4 on 2022-06-26 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modals', '0009_alter_memorandum_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='NoteCategory',
        ),
    ]
